# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_status', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_date', models.DateTimeField(null=True)),
                ('deliver_date', models.DateTimeField(null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('not_found', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='* Full Name')),
                ('mitbbs_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='MITBBS ID')),
                ('endorse_mitbbs_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u80cc\u4e66\u4ebaMITBBS ID')),
                ('email', models.EmailField(max_length=100, verbose_name='* Email')),
                ('phone', models.CharField(max_length=20, verbose_name='* Phone')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('billpay_number', models.CharField(max_length=100, verbose_name='* Pill Pay Number')),
                ('billpay_credit_card_type', models.CharField(max_length=50, verbose_name='* Pill Pay Credit Card Type')),
                ('paid', models.FloatField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Business')),
            ],
            options={
                'db_table': 'user_information',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserInformation'),
        ),
    ]
